### PR TITLE
Fix building with Cabal 1.24

### PR DESCRIPTION
**Pull request by wahjava**
ATM, it fails with following error at `configure` stage:

    /tmp/cabal-tmp-44775/HDBC-mysql-0.6.6.1/dist/setup/setup.hs:31:7: error:
    • Couldn't match expected type ‘ProgramSearchPath
    -> IO (Maybe (FilePath, [FilePath]))’
    with actual type ‘IO (Maybe FilePath)’
    • In a stmt of a 'do' block:
    mysql_config <- findProgramOnPath "mysql_config" verbosity
    In the expression:
    do { mysql_config <- findProgramOnPath "mysql_config" verbosity;
    mysql_config5 <- findProgramOnPath "mysql_config5" verbosity;
    return (mysql_config `mplus` mysql_config5) }
    In the ‘programFindLocation’ field of a record
    )

The attached commit fixes it by switching to `findProgramOnSearchPath` function.

### CODE REVIEW

**Comment by ryantm** [comment]
Thanks for the contribution! 0.6.6.2 builds with Cabal 1.24, so I'm closing this. Please let me know if I'm missing something and I will reopen.

**Comment by wahjava** [comment]
@ryantm I am not sure what makes you say it builds with it, as the source still uses old API.. There is even a build log failure report at Hackage.

http://hackage.haskell.org/package/HDBC-mysql-0.6.6.2/reports/1

HTH

**Comment by ryantm** [comment]
@wahjava I was able to reproduce this using GHC 8.0.1. Before, I was using Cabal 1.24 with ghc 7.10.3 and it built fine. Sorry about the confusion.

**Comment by ryantm** [comment]
Thanks @wahjava I merged your changes in along with updating the constraints on the .cabal file to match the changes. Can you check if a526af2 works for you?
