### ISSUE TITLE
tons of linker errors w/ ghc 7.8.4

### ISSUE THREAD

**Issue by mgmeier** [ryantm/hdbc-mysql#16]
```
/home/mgore/.cabal/lib/x86_64-linux-ghc-7.8.4/HDBC-mysql-0.6.6.1/libHSHDBC-mysql-0.6.6.1.a(Connection__181.o): In Funktion `ci8m_info':
(.text+0x80): Nicht definierter Verweis auf `mysql_query'
/home/mgore/.cabal/lib/x86_64-linux-ghc-7.8.4/HDBC-mysql-0.6.6.1/libHSHDBC-mysql-0.6.6.1.a(Connection__181.o): In Funktion `cifo_info':
(.text+0x120f): Nicht definierter Verweis auf `mysql_real_connect'
/home/mgore/.cabal/lib/x86_64-linux-ghc-7.8.4/HDBC-mysql-0.6.6.1/libHSHDBC-mysql-0.6.6.1.a(Connection__134.o):(.text+0x3a): Nicht definierter Verweis auf `mysql_fetch_field'
/home/mgore/.cabal/lib/x86_64-linux-ghc-7.8.4/HDBC-mysql-0.6.6.1/libHSHDBC-mysql-0.6.6.1.a(Connection__158.o):(.text+0x3a): Nicht definierter Verweis auf `mysql_errno'
/home/mgore/.cabal/lib/x86_64-linux-ghc-7.8.4/HDBC-mysql-0.6.6.1/libHSHDBC-mysql-0.6.6.1.a(Connection__158.o):(.text+0x52): Nicht definierter Verweis auf `mysql_error'
/home/mgore/.cabal/lib/x86_64-linux-ghc-7.8.4/HDBC-mysql-0.6.6.1/libHSHDBC-mysql-0.6.6.1.a(Connection__164.o): In Funktion `chR6_info':
(.text+0xb8): Nicht definierter Verweis auf `mysql_query'
(...)
```
where ```Nicht definierter Verweis auf``` means 'undefined reference to'. This is not an exhaustive list, there are more symbols the linker obviously can't resolve. What could be the problem here? I'm a little helpless with these errors.

BTW: Why didn't you merge the fix for installing with Cabal >= 1.18? The version of hdbc-mysql on hackage sadly is completely unusable ;_;

**Comment by ryantm** [comment]
@mgmeier it looks like the current Cabal file contains a line restricting to Cabal >= 1.18 and it builds fine on 7.8.4 for me, so I'm closing this. Reply if you are still having trouble and I can reopen it.
